/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/AddSquadModal`; params?: Router.UnknownInputParams; } | { pathname: `/components/AddUserModal`; params?: Router.UnknownInputParams; } | { pathname: `/components/ProfileModal`; params?: Router.UnknownInputParams; } | { pathname: `/components/SettingsModal`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/AppNavigator`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/types`; params?: Router.UnknownInputParams; } | { pathname: `/screens/DashboardScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/LoadingScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/NotificationsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/RankingScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/SquadsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/UserListScreen`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/AddSquadModal`; params?: Router.UnknownOutputParams; } | { pathname: `/components/AddUserModal`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ProfileModal`; params?: Router.UnknownOutputParams; } | { pathname: `/components/SettingsModal`; params?: Router.UnknownOutputParams; } | { pathname: `/navigation/AppNavigator`; params?: Router.UnknownOutputParams; } | { pathname: `/navigation/types`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/DashboardScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/LoadingScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/LoginScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/NotificationsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/RankingScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/SquadsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/UserListScreen`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/AddSquadModal${`?${string}` | `#${string}` | ''}` | `/components/AddUserModal${`?${string}` | `#${string}` | ''}` | `/components/ProfileModal${`?${string}` | `#${string}` | ''}` | `/components/SettingsModal${`?${string}` | `#${string}` | ''}` | `/navigation/AppNavigator${`?${string}` | `#${string}` | ''}` | `/navigation/types${`?${string}` | `#${string}` | ''}` | `/screens/DashboardScreen${`?${string}` | `#${string}` | ''}` | `/screens/LoadingScreen${`?${string}` | `#${string}` | ''}` | `/screens/LoginScreen${`?${string}` | `#${string}` | ''}` | `/screens/NotificationsScreen${`?${string}` | `#${string}` | ''}` | `/screens/RankingScreen${`?${string}` | `#${string}` | ''}` | `/screens/SquadsScreen${`?${string}` | `#${string}` | ''}` | `/screens/UserListScreen${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/AddSquadModal`; params?: Router.UnknownInputParams; } | { pathname: `/components/AddUserModal`; params?: Router.UnknownInputParams; } | { pathname: `/components/ProfileModal`; params?: Router.UnknownInputParams; } | { pathname: `/components/SettingsModal`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/AppNavigator`; params?: Router.UnknownInputParams; } | { pathname: `/navigation/types`; params?: Router.UnknownInputParams; } | { pathname: `/screens/DashboardScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/LoadingScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/NotificationsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/RankingScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/SquadsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/UserListScreen`; params?: Router.UnknownInputParams; };
    }
  }
}
