/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/notificacoes` | `/notificacoes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ranking` | `/ranking`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/squads` | `/squads`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/usuarios` | `/usuarios`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/notificacoes` | `/notificacoes`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/ranking` | `/ranking`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/squads` | `/squads`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/usuarios` | `/usuarios`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/notificacoes${`?${string}` | `#${string}` | ''}` | `/notificacoes${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/ranking${`?${string}` | `#${string}` | ''}` | `/ranking${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/squads${`?${string}` | `#${string}` | ''}` | `/squads${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/usuarios${`?${string}` | `#${string}` | ''}` | `/usuarios${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/notificacoes` | `/notificacoes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ranking` | `/ranking`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/squads` | `/squads`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/usuarios` | `/usuarios`; params?: Router.UnknownInputParams; };
    }
  }
}
