spring.application.name=sge-app
# --- Database Configuration (PostgreSQL Docker Local) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA/Hibernate Configuration ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# --- JWT Configuration ---
jwt.secret-key=${JWT_SECRET_KEY}
jwt.expiration=86400000 # 24 horas em milissegundos (para Access Token)
jwt.refresh-expiration=604800000 # 7 dias em milissegundos (para Refresh Token)