spring.application.name=P_I

# Configurações do Banco de Dados
db.url=jdbc:postgresql://localhost:5432/sge
db.username=sg_user
db.password=sprin
db.ssl=true

# Outras configurações da aplicação
app.name=MeuAppDeIA
app.version=1.0.0